### ISSUE TITLE
Code review for Arvind

### ISSUE THREAD

**Issue by nishanthelango** [AY2122S1-CS2113T-W11-4/tp#116]
@Dniv-ra

![image](https://user-images.githubusercontent.com/37863640/139372208-e53c6b2b-f8a3-44c2-b0c4-2b9ec83fd9c4.png)
Avoid deeply nested code. Consider extracting some of the logic into constants.

![image](https://user-images.githubusercontent.com/37863640/139372353-226c137c-79d4-4468-88a6-03150ad50026.png)
Constant names should be in uppercase (e.g logger -> LOGGER)

![image](https://user-images.githubusercontent.com/37863640/139376425-8ca4f852-af71-4c93-bd35-6e9338c98175.png)
Consider extracting strings such as "ingredient" and "dish" into constants

![image](https://user-images.githubusercontent.com/37863640/139377231-3e79a293-9064-49dd-a389-971a14361fe6.png)
You can consider assigning each of these arguments such as params[0] to variables for more clarity.

**Comment by Dniv-ra** [comment]
Fixed issues. Thanks Nishanth!
